name: dt
dependencies:
  - python=3.8
  - requests
  - beautifulsoup4
  - lxml
  - elasticsearch
  - pip:
    - scrapy
    - neo4j
    - pyOpenSSL
    - cryptography
    - pysha3
    - langchain
    - openai
    - python-dotenv
    - pdfminer.six
    - unstructured[all-docs]
    - pytesseract
    - python-magic